version: "3.8"

services:
    estabelesis:
          build: .
          command: npm start
          ports: 
              - 3000:3000
          volumes: 
              - .:/usr/src/app

    mysql-db:
        image: mysql:5.7.31
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - TZ=America/Sao_Paulo
        restart: always    
        ports: 
            - 3308:3308                   
